services:
  backend:
    build:
      context: ./backend
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

